//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NQH_project2_2210900105.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_TRI
    {
        public string admin_username { get; set; }
        public string admin_pass { get; set; }
        public byte admin_status { get; set; }
    }
}
